language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dockerjbc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockerjbc/react-test npm test -- --coverage

after_success:
  - docker build -t dockerjbc/multi-client ./client
  - docker build -t dockerjbc/multi-nginx ./nginx
  - docker build -t dockerjbc/multi-server ./server
  - docker build -t dockerjbc/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
# Take those images and push them to docker hub:
  - docker push dockerjbc/multi-client
  - docker push dockerjbc/multi-nginx
  - docker push dockerjbc/multi-server
  - docker push dockerjbc/multi-worker
